### ISSUE TITLE
CSS doesn't render properly when using HTTPS to load the page

### ISSUE THREAD

**Issue by nyanpasu64** [msjmath/msjmath.github.io#1]
I use HTTPS Everywhere, which encrypts web traffic whenever possible to make it more difficult for casual snoopers to spy on my browsing. This issue appears with both HTTPS Everywhere and normal HTTPS.

However, your HTML <head> has a <base> tag, which forces the CSS to be loaded from non-HTTPS (not sure why HTTPS Everywhere doesn't change the CSS loading). As a result, the CSS will not load on Firefox due to mixed content being blocked.

My suggestion is to either remove the <base> tag and add a leading slash to all the relative URLs in the body, or in the <base> tag, replace "http://" with "//". I'm not experienced enough to know what's the best practice, but I don't exactly think the hardcoded path is a good idea in general.

This problem occurs even without HTTPS Everywhere installed, whenever you're using HTTPS to access the page.

edit: backslashes

**Comment by qwerytiop** [comment]
Ok, got it
