### ISSUE TITLE
Can't git clone to Windows due to invalid filenames in "backup" directory

### ISSUE THREAD

**Issue by nyanpasu64** [msjmath/msjmath.github.io#2]
Title is self-explanatory, Windows doesn't allow pipes in the file names, I don't know if Linux does or not.

Suggestion, either remove or rename.

Is it possible for Git to auto-rename invalid files? If so, I don't know how.

**Comment by qwerytiop** [comment]
^We'll have to fix that eventually.... I could probably do it with a script if I had more time, but not right now.
